version: '2'
services:
  application:
    restart: always
    build: 
      context: ./application
      args:
        - INTERNAL_IP=$INTERNAL_IP
    command: gunicorn -w 4 --bind :5000 wsgi:application
    expose:
     - "5000"
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build: ./nginx
    links:
      - application
    expose:
      - 80
    ports:
      - "80:8080"